name: clim680
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab=1.2.5
  - jupyter_client=5.3.1
  - nbserverproxy
  - netcdf4
  - metpy
  - numpy
  - climpred
  - cfgrib
  - scipy
  - xarray
  - dask
  - xskillscore
  - cartopy
  - matplotlib
  - tqdm
  - ipywidgets
  - eofs 
  - hvplot
  - boto3
  - botocore
  - xesmf
  - esmpy<=7.1.0
  - intake
  - intake-esm
  - gcsfs
  - zarr

